// Generated by CoffeeScript 1.6.3
(function() {
  var canvas, catchDomInfo, messageBox, messageBoxJ, selector, sendNotification, styleObj, targetUrl, updateListeners;

  console.log("wechet extension injected!");

  selector = "#listContainer .message_item";

  targetUrl = "http://42.120.22.130/wechatInDBTest.php";

  canvas = document.createElement("canvas");

  canvas.id = '_wcInject_wrapperCanvas';

  canvas.width = canvas.height = 132;

  document.body.appendChild(canvas);

  canvas.style['display'] = 'none';

  messageBox = document.createElement('div');

  messageBox.id = "_wcInject_msgBox";

  messageBox.innerHTML = "<p id='content'>通知消息</p>";

  document.body.appendChild(messageBox);

  styleObj = {
    position: 'fixed',
    width: '100px',
    top: '15px',
    right: '30px',
    'z-index': '9999',
    'display': 'none',
    'color': 'darkred',
    'border': '1px solid darkgrey',
    'border-radius': '3px',
    'background-color': 'white',
    'text-align': 'center'
  };

  messageBoxJ = $(messageBox);

  messageBoxJ.css(styleObj);

  updateListeners = function() {
    var dom, doms, newButton, _i, _len, _results;
    doms = $(selector);
    if (doms.length === 0) {
      window.setTimeout((function() {
        return updateListeners();
      }), 200);
      return;
    }
    _results = [];
    for (_i = 0, _len = doms.length; _i < _len; _i++) {
      dom = doms[_i];
      newButton = document.createElement("button");
      styleObj = {
        'margin-top': 0,
        'background-color': 'rgb(176, 202, 248)',
        'border': 'none'
      };
      $(newButton).css(styleObj);
      $(newButton).hover((function() {
        $(this).css('background-color', 'rgb(186, 222, 255)');
        return $(this).css('cursor', 'pointer');
      }), (function() {
        $(this).css('background-color', 'rgb(176, 202, 248)');
        return $(this).css('cursor', 'auto');
      }));
      newButton.className = "wcInject_catchBtn";
      newButton.innerHTML = "发送此消息";
      newButton.targetDom = dom;
      newButton.onclick = function() {
        return catchDomInfo(this.targetDom);
      };
      _results.push($(dom).find(".message_opr").append(newButton).css('overflow', 'visible'));
    }
    return _results;
  };

  catchDomInfo = function(targetDom) {
    var arr, c, obj, targetJ, text, _i, _len, _ref;
    console.warn('targetClicked', targetDom);
    targetJ = $(targetDom);
    obj = {
      id: targetJ.attr("data-id"),
      fakeId: targetJ.find('.remark_name').attr("data-fakeid"),
      nickName: targetJ.find('.remark_name').text(),
      key: "1773771",
      avatarImgDataUrl: (function() {
        var context, dataUrl, img, str;
        img = targetJ.find(".avatar img")[0];
        context = canvas.getContext('2d');
        context.drawImage(img, 0, 0);
        dataUrl = canvas.toDataURL('images/jpg');
        str = dataUrl.replace(/^data:image\/(png|jpg);base64,/, "");
        return str;
      })(),
      contentType: (function() {
        var J;
        J = targetJ.find('.wxMsg');
        if (J.find('img').length > 0) {
          return 'img';
        } else {
          return 'text';
        }
      })()
    };
    if (obj.contentType === 'img') {
      obj.content = targetJ.find('.wxMsg img')[0].src;
    } else {
      text = targetJ.find('.wxMsg').text();
      arr = [];
      _ref = text.split(" ");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        c = _ref[_i];
        if (c) {
          arr.push(c);
        }
      }
      obj.content = arr.join('');
    }
    console.log("发送消息", obj);
    return $.ajax({
      type: 'post',
      url: targetUrl,
      data: obj,
      success: function(data, textStatus, jqXHR) {
        console.log('success');
        return sendNotification('发送成功', 1000);
      },
      error: function(data, textStatus, jqXHR) {
        console.error('post failed');
        return sendNotification('发送失败，请联系管理员');
      }
    });
  };

  sendNotification = function(msg, timeout, picUrl, title) {
    if (timeout == null) {
      timeout = 1000;
    }
    if (picUrl == null) {
      picUrl = 'icon.png';
    }
    if (title == null) {
      title = "微信墙管理插件";
    }
    messageBoxJ.find("#content").text(msg);
    return messageBoxJ.slideDown('fast', function() {
      return window.setTimeout((function() {
        return messageBoxJ.slideUp('fast');
      }), timeout);
    });
  };

  window.onload = function() {
    return updateListeners();
  };

}).call(this);
